services:
  pgdatabase:
    image: postgres:latest
    env_file:
      - ../.env
    volumes:
      - "../_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ../.env
    ports:
      - "8080:80"
